### ISSUE TITLE
Update documentation to include configuration of headers

### ISSUE THREAD

**Issue by TraceWilson** [thomasloven/lovelace-auto-entities#455]
The documentation does not include any information related to the configuration of headers.  In my case I'm looking for an option to kick off a script to update some helpers which control the contents of the auto-entities card.  I think some documentation and a couple of use case examples would be helpful (hopefully not only to me).

**Comment by TraceWilson** [comment]
1. Thanks, but that's kinda the challenge.  I can't figure out exactly what goes in the headers: property.
2. If I configure the Auto Entities Card in the GUI, and select the 'CARD' tab under 'CONFIG', there is a field for Header, with an initial value of None.  When I click the "+" next to it, I'm given the options to Choose a Header of Graph, Buttons, Picture.  

![image](https://github.com/user-attachments/assets/8b9e38f9-d5c4-47c8-a535-1d5277d1c774)
 
I think I'd like to add some buttons to call a couple of scripts, but I'm not seeing anything explaining the usage of the Header Buttons.  What can be done with them, what are their limitations?  It would be nice to have this added to the docs, or if it's some functionality provided by another part of Home Assistant, maybe a link to that doc for further research.

**Comment by ildar170975** [comment]
The auto-entities card may be used to populate any card (ofc not every card may be populated - but this is not a concern of auto-entities). 
Here as a default example it is proposed to populate Entities card. 
The standard Entities card may have a header - add it in UI as a stand-alone card (i.e. without auto-entities) and you will see same header. 
Since the Entities card is a standard card - it is covered by it’s own official HA documentation. 
The auto-entities card’s documentation should not include docs for all other cards.

**Comment by ildar170975** [comment]
In short: headers and footers are covered in official docs for Entities card.

**Comment by TraceWilson** [comment]
Ahh, ok, apologies, I didn't realize the header config was a part of the entities card.  Still wrapping my head around how all of Home Assistant fits together.  Thanks for you patience!!
